version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/jslib  # Output directory for compiled JavaScript
    command: npm run dev
